# Data Modeling

## Linear Model

### Linear Regression

In [2]:
import numpy as np
import sklearn.linear_model as linear_model

In [3]:
X = np.array([
    [1],
    [2],
    [3],
    [4],
    [5]
])

y = np.array([2,4,6,8,10])

In [4]:
model = linear_model.LinearRegression()
model.fit(X,y)

print(model.coef_, model.intercept_, sep="\n-----\n")

[2.]
-----
0.0


In [5]:
X_new = np.array([
    [6],
    [7]
])

y_pred = model.predict(X_new)
print(y_pred)

[12. 14.]


##### Mini Project (1)

In [6]:
import sklearn.datasets as datasets
import sklearn.model_selection as model_selection
import sklearn.preprocessing as preprocessing
import sklearn.pipeline as pipeline

In [7]:
# 加载数据
X,y = datasets.load_diabetes(
    return_X_y = True
)

# 划分数据集
X_train, X_test, y_train, y_test = model_selection.train_test_split(
    X, y,
    test_size = 0.2,
    shuffle = True,
    random_state = 42
)

print(
    X,y,sep="\n-----\n"
)

[[ 0.03807591  0.05068012  0.06169621 ... -0.00259226  0.01990749
  -0.01764613]
 [-0.00188202 -0.04464164 -0.05147406 ... -0.03949338 -0.06833155
  -0.09220405]
 [ 0.08529891  0.05068012  0.04445121 ... -0.00259226  0.00286131
  -0.02593034]
 ...
 [ 0.04170844  0.05068012 -0.01590626 ... -0.01107952 -0.04688253
   0.01549073]
 [-0.04547248 -0.04464164  0.03906215 ...  0.02655962  0.04452873
  -0.02593034]
 [-0.04547248 -0.04464164 -0.0730303  ... -0.03949338 -0.00422151
   0.00306441]]
-----
[151.  75. 141. 206. 135.  97. 138.  63. 110. 310. 101.  69. 179. 185.
 118. 171. 166. 144.  97. 168.  68.  49.  68. 245. 184. 202. 137.  85.
 131. 283. 129.  59. 341.  87.  65. 102. 265. 276. 252.  90. 100.  55.
  61.  92. 259.  53. 190. 142.  75. 142. 155. 225.  59. 104. 182. 128.
  52.  37. 170. 170.  61. 144.  52. 128.  71. 163. 150.  97. 160. 178.
  48. 270. 202. 111.  85.  42. 170. 200. 252. 113. 143.  51.  52. 210.
  65. 141.  55. 134.  42. 111.  98. 164.  48.  96.  90. 162. 150. 279.
  92.

In [8]:
pipe = pipeline.Pipeline(
    steps = [
        ("scaler", preprocessing.StandardScaler()),
        ("model", linear_model.LinearRegression())
    ]
)

pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)
y_pred2 = pipe.named_steps["model"].predict(pipe.named_steps["scaler"].transform(X_test))
print(y_pred == y_pred2, y_pred, y_pred2,
      sep = "\n-----\n"
)

r2 = pipe.score(X_test, y_test)
print(r2)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True]
-----
[139.5475584  179.51720835 134.03875572 291.41702925 123.78965872
  92.1723465  258.23238899 181.33732057  90.22411311 108.63375858
  94.13865744 168.43486358  53.5047888  206.63081659 100.12925869
 130.66657085 219.53071499 250.7803234  196.3688346  218.57511815
 207.35050182  88.48340941  70.43285917 188.95914235 154.8868162
 159.36170122 188.31263363 180.39094033  47.99046561 108.97453871
 174.77897633  86.36406656 132.95761215 184.53819483 173

#### Mini Project (2)

In [9]:
import sklearn.datasets as datasets
import sklearn.model_selection as model_selection
import sklearn.impute as impute
import sklearn.preprocessing as preprocessing
import sklearn.compose as compose
import sklearn.linear_model as linear_model
import sklearn.pipeline as pipeline

In [10]:
# numeric_features = ["area", "age", "distance"]
# categorial_features = ["city", "house_type"]

# numeric_pipe = pipeline.Pipeline([
#     ("impute", impute.SimpleImputer(strategy="median")),
#     ("scaler", preprocessing.StandardScaler())
# ])

# categorial_pipe = pipeline.Pipeline([
#     ("impute", impute.SimpleImputer(strategy="most_frequent")),
#     ("encoder", preprocessing.OneHotEncoder(handle_unknown="ignore"))
# ])

# preprocess = compose.ColumnTransformer([
#     ("num", numeric_pipe, numeric_features),
#     ("cat", categorial_pipe, categorial_features)
# ])

# model = pipeline.Pipeline([
#     ("preprocess", preprocess),
#     ("regressor", linear_model.LinearRegression())
# ])

In [11]:
# model.fit(X_train, y_train)
# y_pred = model.predict(X_test)

### LASSO Regression

In [12]:
X,y = datasets.load_diabetes(
    return_X_y = True
)
X_train, X_test, y_train, y_test = model_selection.train_test_split(
    X, y,
    test_size = 0.2,
    shuffle = True,
    random_state = 42
)
model = linear_model.Lasso( alpha = 0.1 )
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

r2 = model.score(X_test, y_test)
print(
    "测试集 R2:", r2, "\n",
    "系数:", model.coef_, "\n",
    "截距:", model.intercept_, "\n",
    "非零系数数量:", (model.coef_ != 0).sum()
)

测试集 R2: 0.4718547867276227 
 系数: [   0.         -152.66477923  552.69777529  303.36515791  -81.36500664
   -0.         -229.25577639    0.          447.91952518   29.64261704] 
 截距: 151.57485282893947 
 非零系数数量: 7


### Rigde Regression

In [13]:
X,y = datasets.load_diabetes(
    return_X_y = True
)

X_train, X_test, y_train, y_test = model_selection.train_test_split(
    X, y,
    test_size = 0.2,
    shuffle = True,
    random_state = 42
)

In [14]:
model = linear_model.Ridge(
    alpha = 1.0
)

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

r2 = model.score(X_test, y_test)
print(
    "测试集 R^2 ", r2, "\n"
    "系数：", model.coef_, "\n"
    "截距: ", model.intercept_, "\n"
)

测试集 R^2  0.41915292635986545 
系数： [  45.36737726  -76.66608563  291.33883165  198.99581745   -0.53030959
  -28.57704987 -144.51190505  119.26006559  230.22160832  112.14983004] 
截距:  152.241675211113 



### ElasticNet Regression

In [15]:
X,y = datasets.load_diabetes(
    return_X_y = True,
)
X_train, X_test, y_train, y_test = model_selection.train_test_split(
    X, y,
    test_size = 0.2,
    shuffle = True,
    random_state = 42
)
model = linear_model.ElasticNet(
    alpha = 0.1,
    l1_ratio = 0.5
)
model.fit(X_train, y_train)
y_pred = model.predict(X_train)
r2 = model.score(X_test, y_test)

print(
    "测试集 R^2:", r2, "\n",
    "系数:", model.coef_, "\n",
    "截距:", model.intercept_, "\n",
    "非零系数数量:", (model.coef_ != 0).sum()
)

测试集 R^2: 0.09865421116113748 
 系数: [ 1.08309211e+01 -9.51378929e-03  3.89068647e+01  2.87792332e+01
  1.03720066e+01  7.19189161e+00 -2.35109789e+01  2.56271600e+01
  3.50737451e+01  2.40712511e+01] 
 截距: 153.50994400357047 
 非零系数数量: 10


#### Mini Project

In [18]:
X,y = datasets.load_diabetes(
    return_X_y = True
)
X_train, X_test, y_train, y_test = model_selection.train_test_split(
    X,y,
    test_size = 0.2,
    random_state = 42,
    shuffle = True
)
models = {
    "LinearRegression": linear_model.LinearRegression(),
    "Ridge": linear_model.Ridge( alpha=1 ),
    "Lasso": linear_model.Lasso( alpha=1 ),
    "ElasticNet": linear_model.ElasticNet( alpha=0.1, l1_ratio=0.5 )
}

In [23]:
for name, model in models.items():
    pipe = pipeline.Pipeline([
        ("scaler", preprocessing.StandardScaler()),
        ("model", model)
    ])

    pipe.fit(X_train, y_train)
    score = pipe.score(X_test, y_test)
    coef = pipe.named_steps["model"].coef_

    print(
        "R^2: ", score,
        "非零系数量: ", (coef != 0).sum(),
        "\n" + "-"*30 + "\n"
    )


R^2:  0.4526027629719195 非零系数量:  10 
------------------------------

R^2:  0.45414652070698236 非零系数量:  10 
------------------------------

R^2:  0.46687670944102466 非零系数量:  9 
------------------------------

R^2:  0.45896958196783777 非零系数量:  10 
------------------------------



### Logistic Regression

In [29]:
X,y = datasets.load_iris(
    return_X_y = True
)

X_train, X_test, y_train, y_test = model_selection.train_test_split(
    X, y,
    test_size = 0.2,
    random_state = 42,
    shuffle = True,
    stratify = y
)

model = linear_model.LogisticRegression(
    max_iter = 1000
)

In [42]:
print(y.shape, y_train.shape, (y_train == 0).sum(), (y_train == 1).sum(), (y_train == 2).sum())

(150,) (120,) 40 40 40


In [43]:
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)

acc = model.score(X_test, y_test)

print(
    "预测类别: ", y_pred[:10],
    "真实类别: ", y_test[:10],
    "测试集 accuracy: ", acc,
)

预测类别:  [0 2 1 1 0 1 0 0 2 1] 真实类别:  [0 2 1 1 0 1 0 0 2 1] 测试集 accuracy:  0.9666666666666667


#### Mini Project

In [67]:
import pandas as pd

data = datasets.load_iris(
    as_frame = True
)
X = data.data
y = data.target

X_train, X_test, y_train, y_test = model_selection.train_test_split(
    X,y,
    test_size = 0.2,
    random_state = 42,
    shuffle = True,
    stratify = y
)

print(type(X_train), X_train)

<class 'pandas.DataFrame'>      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
8                  4.4               2.9                1.4               0.2
106                4.9               2.5                4.5               1.7
76                 6.8               2.8                4.8               1.4
9                  4.9               3.1                1.5               0.1
89                 5.5               2.5                4.0               1.3
..                 ...               ...                ...               ...
37                 4.9               3.6                1.4               0.1
2                  4.7               3.2                1.3               0.2
33                 5.5               4.2                1.4               0.2
52                 6.9               3.1                4.9               1.5
3                  4.6               3.1                1.5               0.2

[120 rows x 4 columns]


In [64]:
pipe = pipeline.Pipeline([
    ("scaler", preprocessing.StandardScaler()),
    ("model", linear_model.LogisticRegression(max_iter=1000))
])
pipe.fit(X_train, y_train)

y_pred = pipe.predict(X_test)
proba = pipe.predict_proba(X_test)
acc = pipe.score(X_test, y_test)

print(
    "预测类别: ", y_pred[:10],
    "预测概率: ", proba[:5],
    "accuracy: ", acc,
    sep = "\n-----\n"
)

预测类别: 
-----
[0 2 1 1 0 1 0 0 2 1]
-----
预测概率: 
-----
[[9.78818005e-01 2.11816311e-02 3.63821812e-07]
 [3.79836951e-03 3.69220168e-01 6.26981463e-01]
 [1.48799040e-01 8.42474895e-01 8.72606441e-03]
 [9.54449962e-02 8.94618634e-01 9.93636953e-03]
 [9.88493051e-01 1.15067767e-02 1.72549650e-07]]
-----
accuracy: 
-----
0.9333333333333333


In [68]:
clf = pipe.named_steps["model"]
coef_df = pd.DataFrame(
    data = clf.coef_,
    columns = X.columns,
    index = clf.classes_
)
coef_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,-1.088945,1.024208,-1.799056,-1.686228
1,0.536337,-0.360487,-0.204074,-0.807957
2,0.552608,-0.663721,2.003130,2.494185


In [69]:
clf.coef_

array([[-1.08894494,  1.02420763, -1.79905609, -1.68622819],
       [ 0.53633654, -0.36048698, -0.20407418, -0.80795703],
       [ 0.5526084 , -0.66372065,  2.00313027,  2.49418523]])

## Neighbors Model

### KNN

#### KNN Classifier

In [70]:
import sklearn.neighbors as neighbors